# Generated by Django 5.2.12 on 2026-03-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_speed', models.FloatField()),
                ('adjusted_speed', models.FloatField()),
                ('traffic_level', models.CharField(max_length=10)),
                ('risk_level', models.CharField(max_length=10)),
                ('eta', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
